Updated README.me
Added `.new` since the `EY::CloudClient` needs to generate a new instance to invoke the `Connection#authenticate!`

Error:

    token = EY::CloudClient.authenticate!( EY_SETTINGS[:username], EY_SETTINGS[:password] )
NoMethodError: undefined method `authenticate!' for EY::CloudClient:Class
	from (irb):12
	from /Users/chaffeqa/.rvm/gems/ruby-1.9.3-p392@gamesadmin/gems/railties-4.0.0.beta1/lib/rails/commands/console.rb:88:in `start'
	from /Users/chaffeqa/.rvm/gems/ruby-1.9.3-p392@gamesadmin/gems/railties-4.0.0.beta1/lib/rails/commands/console.rb:9:in `start'
	from /Users/chaffeqa/.rvm/gems/ruby-1.9.3-p392@gamesadmin/gems/railties-4.0.0.beta1/lib/rails/commands.rb:64:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'